FastMPC ported and added simple objective tests

diff --git a/utils b/utils
--- a/utils
+++ b/utils
@@ -17,6 +17,7 @@ sub_help(){
     echo "Usage: $ProgName <subcommand> [options]\n"
     echo "Subcommands:"
     echo "    build             Build the library"
+    echo "    build-debug       Build the library"
     echo "    clean             Clean all build artifacts"
     echo "    clean-all         Clean all build artifacts and delete build/"
     echo "    cpplint           Lint all of the c++ code using cpplint"
@@ -262,6 +263,44 @@ sub_build() {
     cd ./build/
 
     cmake \
+        -D CMAKE_BUILD_TYPE=Release \
+        -D CMAKE_INSTALL_PREFIX=${CONDA_PREFIX} \
+        -D CMAKE_C_COMPILER=$CC \
+        -D CMAKE_CXX_COMPILER=$CXX \
+        -D CMAKE_INSTALL_LIBDIR=${CONDA_PREFIX}/lib \
+        ..
+    
+    # Stop if the build failed
+    if [[ "$?" != "0" ]]; then
+        cd "$original_wd"
+        return 1;
+    fi
+
+    make -j8
+
+    # Stop if the build failed
+    if [[ "$?" != "0" ]]; then
+        cd "$original_wd"
+        return 1;
+    fi
+
+    cd "$original_wd"
+}
+
+# Build in debug mode
+sub_build-debug() { 
+    original_wd=$(pwd)
+    cd "$(git rev-parse --show-toplevel)"
+
+    util_check_conda
+
+    if ! [ -d ./build/ ]; then
+        mkdir ./build/
+    fi
+    cd ./build/
+
+    cmake \
+        -D CMAKE_BUILD_TYPE=Debug \
         -D CMAKE_INSTALL_PREFIX=${CONDA_PREFIX} \
         -D CMAKE_C_COMPILER=$CC \
         -D CMAKE_CXX_COMPILER=$CXX \
